### ISSUE TITLE
Pandoc error when knitting index.html

### ISSUE THREAD

**Issue by rabutler-usbr** [usbr/RW-RDF-Process-Plot#19]
In the "Load all the libraries you need" section, pandoc throws an error if you have a code block in line 34, which currently reads "**add code block here with packages**"

Not sure why this is happening, but it might have something to do with the code ticks the line before. 

Need to fix this.

**Comment by cfelletter** [comment]
I've also gotten this message

**Comment by rabutler-usbr** [comment]
I cannot recreate the issue. It now seems to work fine, but failed one time when trying to recreate.

**Comment by rabutler-usbr** [comment]
```{r, warning=FALSE, message=FALSE, results=FALSE}
library(RWDataPlyr)
library(tidyverse)
library(RWDataPlyr)
library(scales)
library(devtools)
library(CRSSIO)
library(tidyverse)
```

**Comment by cfelletter** [comment]
It seems like my error was impart based on packrat. I restored it and am working again.
